[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hybrid-automaton"
dynamic = ["version"]
description = "Python framework for real-time and simulation hybrid automata, easily integrable with ROS2 and other environments."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = ['hybrid_automaton', 'autonomy', 'navigation']
authors = [
  { name = "Ryan McKee", email = "ryanmckee47@icloud.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "numpy",
  "asyncio"
]

[project.urls]
Documentation = "https://github.com/Ryan McKee/hybrid-automaton#readme"
Issues = "https://github.com/Ryan McKee/hybrid-automaton/issues"
Source = "https://github.com/Ryan McKee/hybrid-automaton"

[tool.hatch.version]
path = "src/hybrid_automaton/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/hybrid_automaton tests}"

[tool.coverage.run]
source_pkgs = ["hybrid_automaton", "tests"]
branch = true
parallel = true
omit = [
  "src/hybrid_automaton/__about__.py",
]

[tool.coverage.paths]
hybrid_automaton = ["src/hybrid_automaton", "*/hybrid-automaton/src/hybrid_automaton"]
hybrid_automatons = ["src/hybrid_automatons", "*hybrid-automaton/src/hybrid_automatons"]
tests = ["tests", "*/hybrid-automaton/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
