graph TD
    A[hybrid_automaton/automaton]
    B --> C[__pycache__]
    B --> D[generators]
    B --> E[helpers]
    B --> F[__about__.py]
    B --> G[__init__.py]
    B --> H[automaton.py]
    B --> I[guards_resets.py]
    B --> J[integration.py]
    B --> K[state.py]
    B --> L[transition.py]
